# Generated by Django 4.2.3 on 2023-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_file_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'pdf')], default='FILE', verbose_name='file type'),
        ),
    ]
