# Generated by Django 4.2.3 on 2023-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_file_file_alter_file_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
