# Generated by Django 4.2.3 on 2023-07-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_file_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
